apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-pr
  namespace: kargo-helm
spec:
  vars:
  - name: image
    value: ghcr.io/bartpaczkows/guestbook
  - name: repoURL
    value: https://github.com/bartpaczkows/kargo-helm-flow.git
  - name: branch
    value: main
  - name: envPath
  - name: argocdApp

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom( vars.repoURL ).ID }}
        path: ./src
      - branch: ${{ vars.branch }}
        path: ./out
  - uses: yaml-update
    as: update-image
    config:
      path: ./out/${{ vars.envPath }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom( vars.image ).Tag }}
  - uses: copy
    config:
      inPath: ./src/base/feature-flags.yaml
      outPath: ./out/${{ vars.envPath }}/feature-flags.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: git-push
    as: push
    config:
      path: ./out
      generateTargetBranch: true
  - uses: git-open-pr
    as: open-pr
    config:
      repoURL: ${{ vars.repoURL }}
      provider: github
      sourceBranch: ${{ task.outputs['push'].branch }}
      targetBranch: ${{ vars.branch }}
      title: Deploy to ${{ ctx.stage }}
  - uses: git-wait-for-pr
    as: wait-for-pr
    config:
      repoURL: ${{ vars.repoURL }}
      prNumber: ${{ task.outputs['open-pr'].prNumber }}

