---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip1
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/kip1
        - name: argocdApp
          value: kargo-helm-kip1

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip2
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/kip2
        - name: argocdApp
          value: kargo-helm-kip2
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: orange
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/kip3
        - name: argocdApp
          value: kargo-helm-kip3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip4
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/kip4
        - name: argocdApp
          value: kargo-helm-kip4

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: proto
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: pink
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
        - kip1
        - kip2
        - kip3
        - kip4
  - origin:
      kind: Warehouse
      name: features
    sources:
      stages:
        - kip1
        - kip2
        - kip3
        - kip4
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: env/proto
        - name: argocdApp
          value: kargo-helm-proto


# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: sbx
#   namespace: kargo-helm
#   annotations:
#     kargo.akuity.io/color: lime
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: guestbook
#     sources:
#       stages:
#         - proto
#   - origin:
#       kind: Warehouse
#       name: features
#     sources:
#       stages:
#         - proto
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: promote
#         vars:
#         - name: envPath
#           value: env/sbx
#         - name: argocdApp
#           value: kargo-helm-sbx

# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: pre
#   namespace: kargo-helm
#   annotations:
#     kargo.akuity.io/color: gray
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: guestbook
#     sources:
#       stages:
#         - sbx
#   - origin:
#       kind: Warehouse
#       name: features
#     sources:
#       stages:
#         - sbx
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: promote
#         vars:
#         - name: envPath
#           value: env/pre
#         - name: argocdApp
#           value: kargo-helm-pre

# ---
# apiVersion: kargo.akuity.io/v1alpha1
# kind: Stage
# metadata:
#   name: prod
#   namespace: kargo-helm
#   annotations:
#     kargo.akuity.io/color: blue
# spec:
#   requestedFreight:
#   - origin:
#       kind: Warehouse
#       name: guestbook
#     sources:
#       stages:
#         - pre
#   - origin:
#       kind: Warehouse
#       name: features
#     sources:
#       stages:
#         - pre
#   promotionTemplate:
#     spec:
#       steps:
#       - task:
#           name: promote
#         vars:
#         - name: envPath
#           value: env/prod
#         - name: argocdApp
#           value: kargo-helm-prod