---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip1
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/kip1
        - name: argocdApp
          value: kargo-helm-kip1
  verification:
    analysisTemplates:
    - name: integration-test-sucess

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip2
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/kip2
        - name: argocdApp
          value: kargo-helm-kip2
  verification:
    analysisTemplates:
    - name: integration-test-sucess
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: orange
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/kip3
        - name: argocdApp
          value: kargo-helm-kip3
  verification:
    analysisTemplates:
    - name: integration-test-sucess
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: kip4
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/kip4
        - name: argocdApp
          value: kargo-helm-kip4
  verification:
    analysisTemplates:
    - name: integration-test-sucess
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: proto
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: pink
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - kip1
        - kip2
        - kip3
        - kip4
      availabilityStrategy: All  #OneOf (default):
      #requiredSoakTime: 2m #
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/proto
        - name: argocdApp
          value: kargo-helm-proto


---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: sbx-ca1
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: lime
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - pre-ca1
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/sbx-ca1
        - name: argocdApp
          value: kargo-helm-sbx-ca1

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pre-ca1
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: gray
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - proto
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/pre-ca1
        - name: argocdApp
          value: kargo-helm-pre-ca1

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-ca1
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - sbx-ca1
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-pr
        vars:
        - name: envPath
          value: env/prod-ca1
        - name: argocdApp
          value: kargo-helm-prod-ca1

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: sbx-fr3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - pre-fr3
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/sbx-fr3
        - name: argocdApp
          value: kargo-helm-sbx-fr3

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pre-fr3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: sky
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - proto
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/pre-fr3
        - name: argocdApp
          value: kargo-helm-pre-fr3

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-fr3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: fuchsia
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - sbx-fr3
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-pr
        vars:
        - name: envPath
          value: env/prod-fr3
        - name: argocdApp
          value: kargo-helm-prod-fr3

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: sbx-us3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - pre-us3
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/sbx-us3
        - name: argocdApp
          value: kargo-helm-sbx-us3

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pre-us3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - proto
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-sync
        vars:
        - name: envPath
          value: env/pre-us3
        - name: argocdApp
          value: kargo-helm-pre-us3

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-us3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: teal
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      stages:
        - sbx-us3
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-pr
        vars:
        - name: envPath
          value: env/prod-us3
        - name: argocdApp
          value: kargo-helm-prod-us3