apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-wf
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
                namespace: argo
              spec:
                entrypoint: whalesay
                arguments:
                  parameters: # the valueS will get overridden by event payload 
                  - name: message
                    value: hello world 
                  - name: stage
                    value: default-stage   
                  - name: argocdApp
                    value: default-app   
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                    # - name: stage
                    # - name: argocdApp
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}\n Kargo stage: {{inputs.parameters.stage}}\n ArgoCDapp name: {{workflow.parameters.argocdApp}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.stage_name
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataKey: body.argoCDapp_name
              dest: spec.arguments.parameters.2.value